#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Healing);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Staggered);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Dashing);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Invulnerable);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Combat_Dash);
